CREATE DATABASE HR;
USE DATABASE HR;

CREATE TABLE regions(
    REGION_ID INT NOT NULL AUTO_INCREMENT,
    REGION_NAME VARCHAR(35),
    PRIMARY KEY(REGION_ID)
)

CREATE TABLE countries(
    COUNTRY_ID INT NOT NULL AUTO_INCREMENT,
    COUNTRY_NAME VARCHAR(40),
    REGION_ID INT,
    PRIMARY KEY(COUNTRY_ID),
    FOREIGN KEY(REGION_ID) REFERENCES regions(REGION_ID)
)

CREATE TABLE locations(
    LOCATION_ID INT NOT NULL AUTO_INCREMENT,
    STREET_ADDRESS VARCHAR(100),
    POSTAL_CODE VARCHAR(12),
    CITY VARCHAR(30),
    STATE_PROVINVE VARCHAR(12),
    COUNTRY_ID INT,
    PRIMARY KEY(LOCATION_ID),
    FOREIGN KEY(COUNTRY_ID) REFERENCES countries(COUNTRY_ID)
)

CREATE TABLE deparments(
    DEPARMENT_ID INT NOT NULL AUTO_INCREMENT,
    DEPARMENT_NAME VARCHAR(50),
    MANAGER_ID INT,
    LOCATION_ID INT,
    PRIMARY KEY(DEPARMENT_ID),
    FOREIGN KEY(LOCATION_ID) REFERENCES locations(LOCATION_ID)
)

CREATE TABLE jobs(
    JOB_ID INT NOT NULL AUTO_INCREMENT,
    JOB_TITLE VARCHAR(50),
    MIN_SALARY INT,
    MAX_SALARY INT,
    PRIMARY KEY(JOB_ID)
)

CREATE TABLE employees(
    EMPLOYEES_ID INT NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(50),
    PHONE_NUMBER VARCHAR(50),
    HIRE_DATE DATE,
    JOB_ID INT,
    SALARY INT,
    COMMISION_PCT INT,
    MANAGER_ID INT,
    DEPARMENT_ID INT,
    PRIMARY KEY(EMPLOYEES_ID),
    FOREIGN KEY(DEPARMENT_ID) REFERENCES deparments(DEPARMENT_ID),
    FOREIGN KEY(JOB_ID) REFERENCES jobs(JOB_ID)
)

CREATE TABLE job_history(
    EMPLOYEES_ID INT NOT NULL AUTO_INCREMENT,
    START_DATE DATE,
    END_DATE DATE,
    JOB_ID INT,
    DEPARMENT_ID INT,
    PRIMARY KEY(EMPLOYEES_ID),
    FOREIGN KEY(DEPARMENT_ID) REFERENCES deparments(DEPARMENT_ID)
)

DROP DATABASE HR;