CREATE DATABASE inventory;
USE inventory;

CREATE TABLE salesman(
    SALESMAN_ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    CITY VARCHAR(15) NOT NULL,
    COMMISION DECIMAL(5,2),
    PRIMARY KEY('SALESMAN_ID')
)

CREATE TABLE customer(
    CUSTOMER_ID INT NOT NULL AUTO_INCREMENT,
    CUST_NAME VARCHAR(30) NOT NULL,
    CITY VARCHAR(30) NOT NULL,
    GRADE NUMERIC(3) NOT NULL,
    SALESMAN_ID INT,
    PRIMARY KEY(CUSTOMER_ID),
    FOREIGN KEY(SALESMAN_ID) REFERENCES salesman(SALESMAN_ID)
) 

CREATE TABLE orders (
    ORD_NO INT NOT NULL AUTO_INCREMENT,
    PURCH_AMT DECIMAL(8,2),
    ORD_DATE DATE,
    CUSTOMER_ID INT,
    SALESMAN_ID INT,
    PRIMARY KEY(ORD_NO),
    FOREIGN KEY(CUSTOMER_ID) REFERENCES customer(CUSTOMER_ID),
    FOREIGN KEY(SALESMAN_ID) REFERENCES salesman(SALESMAN_ID)
)

DROP DATABASE inventory ;